name:                aoc2022
version:             0.1.0.0
github:              "tomphp/aoc2022"
license:             BSD3
author:              "Tom Oram"
maintainer:          "me@tomoram.io"
copyright:           "Tom Oram"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tomphp/aoc2022#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- text

default-extensions:
- DerivingStrategies
- GeneralizedNewtypeDeriving
- NamedFieldPuns
- OverloadedStrings
- RecordWildCards
- TypeApplications

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  aoc2022-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2022

tests:
  aoc2022-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-missing-export-lists
    dependencies:
    - aoc2022
    - hspec
